#!/bin/bash

source ~/.bashrc 

DOMAIN="magicbot"
export PROBCOG_HOME=$ROSIE_PROJ/probcog

# Run in background
BG="FALSE"

# Iterate over each argument given
while [[ $# -gt 0 ]]
do
	arg="$1"
	case $arg in
		-t|--tabletop)
			export PROBCOG_HOME=$ROSIE_PROJ/tabletop
			DOMAIN="tabletop"
			;;
		-f|--fetch)
			export PROBCOG_HOME=$ROSIE_PROJ/fetch
			DOMAIN="fetch"
			;;
		-m|--magicbot)
			export PROBCOG_HOME=$ROSIE_PROJ/probcog
			DOMAIN="magicbot"
			;;
		-b|--background)
			BG="TRUE"
			;;
		*)
			WORLD_FILE=$1
			;;
	esac
	shift
done

if [ "$WORLD_FILE" == "" ]; then 
	echo "Missing world file"
	exit 1
fi

WORLD_FILE=$PROBCOG_HOME/worlds/$WORLD_FILE

export CLASSPATH=$CLASSPATH:$PROBCOG_HOME/java/probcog.jar

cd $PROBCOG_HOME
if [ "$DOMAIN" == "tabletop" ]; then
	if [ "$BG" == "TRUE" ]; then
		java probcog.gui.PerceptionGUI -w $WORLD_FILE -c $PROBCOG_HOME/config/probcog.config &
	else
		java probcog.gui.PerceptionGUI -w $WORLD_FILE -c $PROBCOG_HOME/config/probcog.config
	fi
elif [ "$DOMAIN" == "fetch" ]; then
	if [ "$BG" == "TRUE" ]; then
		java probcog.gui.PerceptionGUI -w $WORLD_FILE -c $PROBCOG_HOME/config/probcog.config -k &
	else
		java probcog.gui.PerceptionGUI -w $WORLD_FILE -c $PROBCOG_HOME/config/probcog.config -k
	fi
elif [ "$DOMAIN" == "magicbot" ]; then
	export PROBCOG_CONFIG=$PROBCOG_HOME/config/robot.config.local
	if [ "$BG" == "TRUE" ]; then
		java probcog.gui.MobileGUI -w $WORLD_FILE &
	else
		java probcog.gui.MobileGUI -w $WORLD_FILE
	fi
fi
